language: minimal

services:
  - docker

install:
  - docker pull jjmerelo/test-perl6
  - docker images
  - docker run -t --entrypoint="/bin/sh" jjmerelo/test-perl6  -c "apk add openssl-dev"
  
script: docker run -t -v $TRAVIS_BUILD_DIR:/test jjmerelo/test-perl6
